# Generated by Django 5.0.6 on 2025-12-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.BigIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('installs', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=200, null=True)),
                ('genres', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=200, null=True)),
                ('current_version', models.CharField(blank=True, max_length=200, null=True)),
                ('android_version', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=1000)),
                ('translated_review', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=200, null=True)),
                ('sentiment_polarity', models.FloatField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set', to='googlePlayStoreAppsDetails.app')),
            ],
        ),
    ]
